ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS';

CREATE OR REPLACE PACKAGE Lab6func AS
FUNCTION getDate RETURN DATE;
END Lab6func;
/
CREATE PACKAGE BODY Lab6func AS
FUNCTION getDate RETURN DATE IS
newday DATE := SYSDATE;
BEGIN
RETURN newday;
END;
END Lab6func;
/

