ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS';

CREATE OR REPLACE PACKAGE Lab6func AS
FUNCTION getDate RETURN DATE;
FUNCTION userInfo RETURN VARCHAR2;
END Lab6func;
/
CREATE OR REPLACE PACKAGE BODY Lab6func AS
FUNCTION getDate RETURN DATE IS
newday DATE := SYSDATE;
BEGIN
RETURN newday;
END getDate;

FUNCTION userInfo RETURN VARCHAR2 IS
BEGIN
RETURN user;
END userInfo;

END Lab6func;
/

