/*Trigger for generating PK for ON INSERT*/
DROP SEQUENCE newID;
CREATE SEQUENCE newID 
MINVALUE 1
INCREMENT BY 5
START WITH 1;
CREATE OR REPLACE TRIGGER onInsert
AFTER INSERT ON Student
FOR EACH ROW
BEGIN
INSERT INTO STUDENT(STDID)
VALUES(newID.NEXTVAL);
END;
/
